---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - First author
  - Another author
thanks: "Code and data are available at: LINK."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references_datasheet.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Extract of the questions from @gebru2021datasheets


**Motivation**

1. *For what purpose was the dataset created? Was there a specific task in mind? Was there a specific gap that needed to be filled? Please provide a description.*
    - The dataset was created to record the Toronto Police Budget for the 2021 fiscal year.
2. *Who created the dataset (for example, which team, research group) and on behalf of which entity (for example, company, institution, organization)?*
    - The dataset was published by the Toronto Police Services on behalf of the City of Toronto.
3. *Who funded the creation of the dataset? If there is an associated grant, please provide the name of the grantor and the grant name and number.*
    - The data was funded by the City of Toronto as it is a governmental responsibility. 
4. *Any other comments?*
    - TBD

**Composition**

1. *What do the instances that comprise the dataset represent (for example, documents, photos, people, countries)? Are there multiple types of instances (for example, movies, users, and ratings; people and interactions between them; nodes and edges)? Please provide a description.*
	- The instances in the dataset represent expenditures for the police force. There is one type of instance, the expense on the budget and its corresponding descriptions.
2. *How many instances are there in total (of each type, if appropriate)?*
	- There is one instance in total. 
3. *Does the dataset contain all possible instances or is it a sample (not necessarily random) of instances from a larger set? If the dataset is a sample, then what is the larger set? Is the sample representative of the larger set (for example, geographic coverage)? If so, please describe how this representativeness was validated/verified. If it is not representative of the larger set, please describe why not (for example, to cover a more diverse range of instances, because instances were withheld or unavailable).*
	- The dataset contains all possible instances for the budget, it is the observational data for the Toronto Police Service.
4. *What data does each instance consist of? "Raw" data (for example, unprocessed text or images) or features? In either case, please provide a description.*
	- each instance contains raw data that describes the expense on the budget.
5. *Is there a label or target associated with each instance? If so, please provide a description.*
	- There is a label associated with the instance, there is a unique ID variable for each data point.
6. *Is any information missing from individual instances? If so, please provide a description, explaining why this information is missing (for example, because it was unavailable). This does not include intentionally removed information, but might include, for example, redacted text.*
	- There were four missing variables within the instance for the budget, it was unavailble and not accessible. 
7. *Are relationships between individual instances made explicit (for example, users' movie ratings, social network links)? If so, please describe how these relationships are made explicit.*
	- There are no relationships between individual instances. 
8. *Are there recommended data splits (for example, training, development/validation, testing)? If so, please provide a description of these splits, explaining the rationale behind them.*
	- There are no recommended data splits. 
9. *Are there any errors, sources of noise, or redundancies in the dataset? If so, please provide a description.*
	- TBD
10. *Is the dataset self-contained, or does it link to or otherwise rely on external resources (for example, websites, tweets, other datasets)? If it links to or relies on external resources, a) are there guarantees that they will exist, and remain constant, over time; b) are there official archival versions of the complete dataset (that is, including the external resources as they existed at the time the dataset was created); c) are there any restrictions (for example, licenses, fees) associated with any of the external resources that might apply to a dataset consumer? Please provide descriptions of all external resources and any restrictions associated with them, as well as links or other access points, as appropriate.*
	- TBD
11. *Does the dataset contain data that might be considered confidential (for example, data that is protected by legal privilege or by doctor-patient confidentiality, data that includes the content of individuals' non-public communications)? If so, please provide a description.*
	- TBD
12. *Does the dataset contain data that, if viewed directly, might be offensive, insulting, threatening, or might otherwise cause anxiety? If so, please describe why.*
	- TBD
13. *Does the dataset identify any sub-populations (for example, by age, gender)? If so, please describe how these subpopulations are identified and provide a description of their respective distributions within the dataset.*
	- TBD
14. *Is it possible to identify individuals (that is, one or more natural persons), either directly or indirectly (that is, in combination with other data) from the dataset? If so, please describe how.*
	- TBD
15. *Does the dataset contain data that might be considered sensitive in any way (for example, data that reveals race or ethnic origins, sexual orientations, religious beliefs, political opinions or union memberships, or locations; financial or health data; biometric or genetic data; forms of government identification, such as social security numbers; criminal history)? If so, please provide a description.*
	- TBD
16. *Any other comments?*
	- TBD

**Collection process**

1. *How was the data associated with each instance acquired? Was the data directly observable (for example, raw text, movie ratings), reported by subjects (for example, survey responses), or indirectly inferred/derived from other data (for example, part-of-speech tags, model-based guesses for age or language)? If the data was reported by subjects or indirectly inferred/derived from other data, was the data validated/verified? If so, please describe how.*
	- The data was directly observable raw data in a csv file. All the data was  validated by the City of Toronto.
2. *What mechanisms or procedures were used to collect the data (for example, hardware apparatuses or sensors, manual human curation, software programs, software APIs)? How were these mechanisms or procedures validated?*
	- The data was collected directly by the Toronto Police Service. 
3. *If the dataset is a sample from a larger set, what was the sampling strategy (for example, deterministic, probabilistic with specific sampling probabilities)?*
	- The data is not a sample.
4. *Who was involved in the data collection process (for example, students, crowdworkers, contractors) and how were they compensated (for example, how much were crowdworkers paid)?*
	- Employees from the Toronto Police Service were involved in the data collection process, they were compensated with governmental salaries. 
5. *Over what timeframe was the data collected? Does this timeframe match the creation timeframe of the data associated with the instances (for example, recent crawl of old news articles)? If not, please describe the timeframe in which the data associated with the instances was created.*
	- The data was collected over the 2021 fiscal year, it does match instance. 
6. *Were any ethical review processes conducted (for example, by an institutional review board)? If so, please provide a description of these review processes, including the outcomes, as well as a link or other access point to any supporting documentation.*
	- The expenses were reviewed by the Toronto Police Services Board and the City Council.
7. *Did you collect the data from the individuals in question directly, or obtain it via third parties or other sources (for example, websites)?*
	- The data was collected via third party from the Open Data Toronto portal.
8. *Were the individuals in question notified about the data collection? If so, please describe (or show with screenshots or other information) how notice was provided, and provide a link or other access point to, or otherwise reproduce, the exact language of the notification itself.*
	- The individuals at Open Data were not notified about the data collection.
9. *Did the individuals in question consent to the collection and use of their data? If so, please describe (or show with screenshots or other information) how consent was requested and provided, and provide a link or other access point to, or otherwise reproduce, the exact language to which the individuals consented.*
	- The individuals did consent to the use of the data, the purpose of the dataset was to provide open access through the Open Data Toronto portal since it is governmental information. The consent was provided in their license information, https://open.toronto.ca/open-data-license/ 
10. *If consent was obtained, were the consenting individuals provided with a mechanism to revoke their consent in the future or for certain uses? If so, please provide a description, as well as a link or other access point to the mechanism (if appropriate).*
	- Consent cannot be revoked since it was developed through public consultation with the government. 
11. *Has an analysis of the potential impact of the dataset and its use on data subjects (for example, a data protection impact analysis) been conducted? If so, please provide a description of this analysis, including the outcomes, as well as a link or other access point to any supporting documentation.*
	- There has not been an analysis of the potential impact of the dataset. 
12. *Any other comments?*
	- TBD

**Preprocessing/cleaning/labeling**

1. *Was any preprocessing/cleaning/labeling of the data done (for example, discretization or bucketing, tokenization, part-of-speech tagging, SIFT feature extraction, removal of instances, processing of missing values)? If so, please provide a description. If not, you may skip the remaining questions in this section.*
	- Missing values were removed and unnecessary columns were removed.
2. *Was the "raw" data saved in addition to the preprocessed/cleaned/labeled data (for example, to support unanticipated future uses)? If so, please provide a link or other access point to the "raw" data.*
	- The raw data is saved on the Open Data Toronto portal: https://open.toronto.ca/dataset/toronto-police-budget/
3. *Is the software that was used to preprocess/clean/label the data available? If so, please provide a link or other access point.*
	- `R statistical programming` was used to process and clean the data [@citeR]. 
4. *Any other comments?*
	- TBD

**Uses**

1. *Has the dataset been used for any tasks already? If so, please provide a description.*
	- The dataset was used to examine the variables within, used for tables, plots, and summary statistics. The data was also manipulated and used for a multiple linear regression model.
2. *Is there a repository that links to any or all papers or systems that use the dataset? If so, please provide a link or other access point.*
	- There is no repository to all papers or systems that use the dataset.
3. *What (other) tasks could the dataset be used for?*
	- The dataset can be used for policy planning regarding government budgets. Additionally, it can be used to analyze safety in the city of Toronto.
4. *Is there anything about the composition of the dataset or the way it was collected and preprocessed/cleaned/labeled that might impact future uses? For example, is there anything that a dataset consumer might need to know to avoid uses that could result in unfair treatment of individuals or groups (for example, stereotyping, quality of service issues) or other risks or harms (for example, legal risks, financial harms)? If so, please provide a description. Is there anything a dataset consumer could do to mitigate these risks or harms?*
	- The dataset is a breakdown of the approved budget for Toronto Police Service, risks involving financials for different classifications within the police force may arise. 
5. *Are there tasks for which the dataset should not be used? If so, please provide a description.*
	- The dataset should not be used for topics not involving the expenditures of the police force, as that is the only suitable utilization of this data. 
6. *Any other comments?*
	- TBD

**Distribution**

1. *Will the dataset be distributed to third parties outside of the entity (for example, company, institution, organization) on behalf of which the dataset was created? If so, please provide a description.*
	- It is possible the dataset may be distributed within the municipal government, but to my knowledge there has been no distribution besides its availability on Open Data Toronto.
2. *How will the dataset be distributed (for example, tarball on website, API, GitHub)? Does the dataset have a digital object identifier (DOI)?*
	- The dataset is available on Open Data Toronto, the unique identifier for getting the package is 668434ee-9541-40a8-adb6-0ad805fcc9b6. 
3. *When will the dataset be distributed?*
	- The dataset was last refreshed in October 20, 2021.
4. *Will the dataset be distributed under a copyright or other intellectual property (IP) license, and/or under applicable terms of use (ToU)? If so, please describe this license and/ or ToU, and provide a link or other access point to, or otherwise reproduce, any relevant licensing terms or ToU, as well as any fees associated with these restrictions.*
	- The dataset is distributed under an Open Government License, a link: https://open.toronto.ca/open-data-license/
5. *Have any third parties imposed IP-based or other restrictions on the data associated with the instances? If so, please describe these restrictions, and provide a link or other access point to, or otherwise reproduce, any relevant licensing terms, as well as any fees associated with these restrictions.*
	- There have been no imposed restrictions.
6. *Do any export controls or other regulatory restrictions apply to the dataset or to individual instances? If so, please describe these restrictions, and provide a link or other access point to, or otherwise reproduce, any supporting documentation.*
	- Regulatory restrictions from the City of Toronto must apply. 
7. *Any other comments?*
	- TBD

**Maintenance**

1. *Who will be supporting/hosting/maintaining the dataset?*
	- The dataset is maintained by the Toronto Police Services
2. *How can the owner/curator/manager of the dataset be contacted (for example, email address)?*
	- The Toronto Police Service can be contacted by email:     Analytics.Innovation@torontopolice.on.ca
3. *Is there an erratum? If so, please provide a link or other access point.*
	- There is no erratum.
4. *Will the dataset be updated (for example, to correct labeling errors, add new instances, delete instances)? If so, please describe how often, by whom, and how updates will be communicated to dataset consumers (for example, mailing list, GitHub)?*
	- It is refreshed annually by the Toronto Police Services.
5. *If the dataset relates to people, are there applicable limits on the retention of the data associated with the instances (for example, were the individuals in question told that their data would be retained for a fixed period of time and then deleted)? If so, please describe these limits and explain how they will be enforced.*
	- The dataset does not relate to people or any individuals. 
6. *Will older versions of the dataset continue to be supported/hosted/maintained? If so, please describe how. If not, please describe how its obsolescence will be communicated to dataset consumers.*
	- The 2020 fiscal year budget will continue to be maintained by being refreshed annually on the Open Data Toronto portal.
7. *If others want to extend/augment/build on/contribute to the dataset, is there a mechanism for them to do so? If so, please provide a description. Will these contributions be validated/verified? If so, please describe how. If not, why not? Is there a process for communicating/distributing these contributions to dataset consumers? If so, please provide a description.*
	- If others want to augment the dataset they can use the "For Developers" section to copy and paste the code in their respective coding language. Their contributions will not be verified. There is no process of communicating to dataset consumers.
8. *Any other comments?*
	- TBD


\newpage

# References
